base_config: configs/clinicdb_wbsnet.yaml

experiment:
  name: clinicdb_unet_baseline
  tags: ["baseline", "unet", "resnet34"]

model:
  use_wavelet: false
  use_lfsa: false
  use_hfba: false
  boundary_supervision: false
